In [1]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:
hello_constant= tf.constant('Hello World')
hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [6]:

import tensorflow as tf
#Create tensorflow object called tensor
hello_constant= tf.constant('Hello World')

with tf.compat.v1.Session() as sess:
  output= sess.run(hello_constant)
  print(output)

b'Hello World'


In Tensorflow, data isn't stored as integers, floats or strings.These values are encapsulated in an object called tensor. In the case of hello_constant= tf.constant('Hello World'), hello_constant is a 0 dimensional string tensor, but tensors comes in variety of sizes as shown

In [8]:
#A 0 dimensional int 32 tensor
A= tf.constant(1234)


#B is a 1 dimensional int 32 tensor
B= tf.constant([123, 456, 789])

#C is a 2 dimensional int32 tensor
c= tf.constant([[123,456, 789],[222,333,444]])


In [20]:
with tf.Graph(). as_default():
  c1= tf.constant(4,dtype=tf.float64, name='c')
  c2= tf.constant(4,dtype=tf.int32, name='c')
  c3= tf.constant(4,dtype=tf.int32, name='c')


  print(output)

print(c1.name)
print(c2.name)
print(c3.name)


b'Hello World'
c:0
c_1:0
c_2:0


In [13]:
with tf.Graph(). as_default():
  c1= tf.constant(4,dtype=tf.float64, name='c')

with tf.name_scope("prefix_name"):                     #name_scope together many variable in one group for example we have c_1, c_2, c_3 and so on etc we can make these all in one group for easy understanding
  c2=tf.constant(4, dtype=tf.float64, name='c')
  c3= tf.constant(4, dtype=tf.float64,name='c')

print(c1.name)
print(c2.name)
print(c3.name)
print(c1)

c:0
prefix_name_1/c:0
prefix_name_1/c_1:0
Tensor("c:0", shape=(), dtype=float64)


In [17]:
#Another way to run seesion
C= tf.constant([[123, 456, 789],[222,333,444]])
sess= tf.compat.v1.Session()
sess.run(C)

array([[123, 456, 789],
       [222, 333, 444]], dtype=int32)

Graphs: Graphs is made of nodes and edges here nodes represent operation such as add, multiplication etc
Edges represents data passing

In [43]:
init_val= tf.random.normal((1,5),0,1)
var= tf.Variable(init_val, name='var')
print("pre run: \n{}".format(var))
init= tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as sess:
  pot=sess.run(init)
  post_var = sess.run(var)
print("\npost run: \n{}".format(post_var))

pre run: 
<tf.Variable 'var_21:0' shape=(1, 5) dtype=float32>

post run: 
[[-0.549636    0.3903886   0.38740787  1.9361684   0.9477618 ]]


Note: To reuse same variable, we can use the tf.get_variables()function instead of tf.Vraibale()




Tensorflow Input:
In the last section tensorflow was passed into a session and it returned the result. What if we want to use a non-constant? This is where tf.placeholder() and feed_dict come into place. In this section we will go over the basics of feeding data into Tensorflow



tf.placeholder()
Sadly you can't ust set x to your dataset and put in Tensorflow, beacuse overtime you'll want your Tensorflow model to take in different datasets with different parameters. You need tf.placeholder()!

tf.placeholder() returns a tensor that gets its value from data passed tot he tf.session.run() allowing you to set the input right before the session runs:

Session's feed_dict


In [46]:
x= tf.compat.v1.placeholder(tf.string)

with tf.compat.v1.Session() as sess:
  output = sess.run(x,feed_dict={x: 'test'})
  print(output)

test


In [52]:
x= tf.compat.v1.placeholder(tf.string)
y= tf.compat.v1.placeholder(tf.int32)
z= tf.compat.v1.placeholder(tf.float32)
with tf.compat.v1.Session() as sess:
  output_x= sess.run(x, feed_dict={x: 'Test String', y:123 , z:45.67})
  output_y= sess.run(y, feed_dict={x: 'Test String', y:123 , z:45.67})
  print(output_x)
  print(output_y)


Test String
123


In [56]:
x= tf.compat.v1.placeholder("float",None)
y= x ** 2
with tf.compat.v1.Session() as session:
  result= session.run(y, feed_dict={x:[1,2,3]})
print(result)

[1. 4. 9.]


# **Tesnor Flow MATH**

In [57]:
#Addition

x= tf.add(5,2)
with tf.compat.v1.Session() as sess:
  output = sess.run(x)
  print(output)

7


In [60]:
y=tf.subtract(tf.constant(2.0), tf.constant(1.0))
with tf.compat.v1.Session() as sess:
  output = sess.run(y)
  print(output)

1.0


In [66]:
y=tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1)) #1
with tf.compat.v1.Session() as sess:
  output = sess.run(y)
  print(output)

1


In [67]:
import tensorflow as tf

x= tf.constant(10)
y= tf.constant(2)
z= tf.subtract(tf.divide(x,y),1)

with tf.compat.v1.Session() as sess:
  output = sess.run(z)
  print(output)


4.0


In [74]:
import tensorflow as tf

a = tf.add(2,5)
b = tf.math.multiply(a,3)
#Startup session using default graph
sess= tf.compat.v1.Session()
#Define deictionary that replace the value of a with 15
replace_dict={a:15}
#Run the session, passing in replce_dict as the value to feed_dict
output= sess.run(b, feed_dict=replace_dict)
print(output)

45


# TensorFlow Sotfmax


In [75]:
x= tf.nn.softmax([2.0, 1.0, 0.2])


In [85]:
import tensorflow as tf


def run_2():
  output = None
  logit_data= [19,35, 354, 45, 354, 54]
  logits= tf.compat.v1.placeholder(tf.float32)


  softmax= tf.nn.softmax(logits)


  with tf.compat.v1.Session() as sess:
    output= sess.run(softmax, feed_dict={logits:logit_data})

  return output


print(run_2())


[0.  0.  0.5 0.  0.5 0. ]


# Cross Entropy

In [91]:
import tensorflow as tf

softmax_data= [0.7, 0.2,0.1]
one_hot_data= [1.0, 0.0, 0.0]


softmax= tf.compat.v1.placeholder(tf.float32)
one_hot= tf.compat.v1.placeholder(tf.float32)


#Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.math.log(softmax)))

with tf.compat.v1.Session() as sess:
  output = sess.run(cross_entropy, feed_dict={one_hot: one_hot_data, softmax: softmax_data})
  print(output)

0.35667497
